// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWAPI.Library.DataAccess;

namespace SWAPI.Library.Migrations
{
    [DbContext(typeof(SWAPIContext))]
    partial class SWAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("SWAPI.Library.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BirthYear");

                    b.Property<string>("Created");

                    b.Property<string>("Edited");

                    b.Property<string>("EyeColor");

                    b.Property<string>("Gender");

                    b.Property<string>("HairColor");

                    b.Property<string>("Height");

                    b.Property<string>("Homeworld");

                    b.Property<string>("Mass");

                    b.Property<string>("Name");

                    b.Property<string>("SkinColor");

                    b.Property<string>("Url");

                    b.HasKey("PersonId");

                    b.ToTable("People");
                });
#pragma warning restore 612, 618
        }
    }
}
